In [3]:
import kagglehub 
from kagglehub import KaggleDatasetAdapter 
import pandas as pd

# Read a .csv from a URL with Pandas

website: https://www.football-data.co.uk/data.php

In [6]:
df_premier24 = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,
    "siddhrajthakor/fbref-premier-league-202425-player-stats-dataset",
    "fbref_PL_2024-25.csv"  

);

C:\Users\84349\AppData\Local\Temp\ipykernel_12816\2088182545.py:1: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df_premier24 = kagglehub.load_dataset(

In [7]:
df_premier24

,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,...,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1
0,1,Max Aarons,eng ENG,DF,Bournemouth,24.0,2000.0,3,1,86,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,2,Joshua Acheampong,eng ENG,DF,Chelsea,18.0,2006.0,4,2,170,...,0.00,0.00,0.00,0.00,0.00,0.12,0.00,0.12,0.12,0.12
2,3,Tyler Adams,us USA,MF,Bournemouth,25.0,1999.0,28,21,1965,...,0.00,0.14,0.14,0.00,0.14,0.07,0.05,0.12,0.07,0.12
3,4,Tosin Adarabioyo,eng ENG,DF,Chelsea,26.0,1997.0,22,15,1409,...,0.06,0.06,0.13,0.06,0.13,0.06,0.01,0.07,0.06,0.07
4,5,Simon Adingra,ci CIV,"FW,MF",Brighton,22.0,2002.0,29,12,1097,...,0.16,0.16,0.33,0.16,0.33,0.20,0.20,0.40,0.20,0.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
569,570,Ashley Young,eng ENG,DF,Everton,39.0,1985.0,32,19,1875,...,0.05,0.14,0.19,0.05,0.19,0.01,0.11,0.12,0.01,0.12
570,571,Illia Zabarnyi,ua UKR,DF,Bournemouth,21.0,2002.0,36,35,3109,...,0.00,0.03,0.03,0.00,0.03,0.04,0.02,0.06,0.04,0.06
571,572,Oleksandr Zinchenko,ua UKR,"DF,MF",Arsenal,27.0,1996.0,15,5,527,...,0.00,0.17,0.17,0.00,0.17,0.11,0.03,0.14,0.11,0.14
572,573,Joshua Zirkzee,nl NED,"FW,MF",Manchester Utd,23.0,2001.0,32,14,1402,...,0.19,0.06,0.26,0.19,0.26,0.31,0.10,0.41,0.31,0.41
573,574,Martin Ødegaard,no NOR,MF,Arsenal,25.0,1998.0,30,26,2325,...,0.12,0.31,0.43,0.08,0.39,0.19,0.21,0.40,0.16,0.37

In [8]:
df_premier24.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 574 entries, 0 to 573
Data columns (total 36 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Rk          574 non-null    int64
 1   Player      574 non-null    object
 2   Nation      570 non-null    object
 3   Pos         574 non-null    object
 4   Squad       574 non-null    object
 5   Age         570 non-null    float64
 6   Born        570 non-null    float64
 7   MP          574 non-null    int64
 8   Starts      574 non-null    int64
 9   Min         574 non-null    int64
 10  90s         574 non-null    float64
 11  Gls         574 non-null    int64
 12  Ast         574 non-null    int64
 13  G+A         574 non-null    int64
 14  G-PK        574 non-null    int64
 15  PK          574 non-null    int64
 16  PKatt       574 non-null    int64
 17  CrdY        574 non-null    int64
 18  CrdR        574 non-null    int64
 19  xG          574 non-null    float64
 20  npxG        574 non-null    float64
 21  xAG         574 non-null    float64
 22  npxG+xAG    574 non-null    float64
 23  PrgC        574 non-null    int64
 24  PrgP        574 non-null    int64
 25  PrgR        574 non-null    int64
 26  Gls.1       574 non-null    float64
 27  Ast.1       574 non-null    float64
 28  G+A.1       574 non-null    float64
 29  G-PK.1      574 non-null    float64
 30  G+A-PK      574 non-null    float64
 31  xG.1        574 non-null    float64
 32  xAG.1       574 non-null    float64
 33  xG+xAG      574 non-null    float64
 34  npxG.1      574 non-null    float64
 35  npxG+xAG.1  574 non-null    float64
dtypes: float64(17), int64(15), object(4)
memory usage: 161.6+ KB

In [9]:
#khám phá dữ liệu
# in ra kích thước dataset

In [11]:
df_premier24.shape

(574, 36)

In [12]:
df_premier24.columns

Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', 'MP', 'Starts',
       'Min', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY',
       'CrdR', 'xG', 'npxG', 'xAG', 'npxG+xAG', 'PrgC', 'PrgP', 'PrgR',
       'Gls.1', 'Ast.1', 'G+A.1', 'G-PK.1', 'G+A-PK', 'xG.1', 'xAG.1',
       'xG+xAG', 'npxG.1', 'npxG+xAG.1'],
      dtype='object')

In [13]:
df_premier24.isna().sum()

Rk            0
Player        0
Nation        4
Pos           0
Squad         0
Age           4
Born          4
MP            0
Starts        0
Min           0
90s           0
Gls           0
Ast           0
G+A           0
G-PK          0
PK            0
PKatt         0
CrdY          0
CrdR          0
xG            0
npxG          0
xAG           0
npxG+xAG      0
PrgC          0
PrgP          0
PrgR          0
Gls.1         0
Ast.1         0
G+A.1         0
G-PK.1        0
G+A-PK        0
xG.1          0
xAG.1         0
xG+xAG        0
npxG.1        0
npxG+xAG.1    0
dtype: int64

In [38]:
# rename
df_premier24.head()
df_premier24.rename(
    columns = {
        'Rk':"Rank" ,
        'Player':"tên cầu thủ" , 
        'Nation':'Quốc tịch',
        "Squad": "Câu_lạc_bộ",
        "Age": "Tuổi",
        "Born": "Năm_sinh",
        "MP": "Số_trận",
        "Starts": "Đá_chính",
        "Min": "Phút_thi_đấu",
        "90s": "Số_trận_90p",
        "Gls.1": "Bàn_thắng",
        "Ast.1": "Kiến_tạo",
        "G+A.1": "Bàn+KT",
        "G-PK.1": "Bàn_không_pen",
        "PK": "Pen_thành_công",
        "PKatt": "Sút_pen",
        "CrdY": "Thẻ_vàng",
        "CrdR": "Thẻ_đỏ",
        "xG.1": "Bàn_kỳ_vọng",
        "npxG.1": "Bàn_không_pen_kỳ_vọng",
        "xAG.1": "Kiến_tạo_kỳ_vọng",
        "npxG+xAG.1": "Hiệu_suất_tấn_công_kỳ_vọng",
        "PrgC": "Dẫn_bóng_tiến",
        "PrgP": "Chuyền_tiến",
        "PrgR": "Nhận_bóng_tiến"
    },
  inplace = True 
)

In [36]:
df_premier24

,Rank,tên cầu thủ,Quốc tịch,Pos,Squad,Age,Born,MP,Starts,Min,...,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1
0,1,Max Aarons,eng ENG,DF,Bournemouth,24.0,2000.0,3,1,86,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,2,Joshua Acheampong,eng ENG,DF,Chelsea,18.0,2006.0,4,2,170,...,0.00,0.00,0.00,0.00,0.00,0.12,0.00,0.12,0.12,0.12
2,3,Tyler Adams,us USA,MF,Bournemouth,25.0,1999.0,28,21,1965,...,0.00,0.14,0.14,0.00,0.14,0.07,0.05,0.12,0.07,0.12
3,4,Tosin Adarabioyo,eng ENG,DF,Chelsea,26.0,1997.0,22,15,1409,...,0.06,0.06,0.13,0.06,0.13,0.06,0.01,0.07,0.06,0.07
4,5,Simon Adingra,ci CIV,"FW,MF",Brighton,22.0,2002.0,29,12,1097,...,0.16,0.16,0.33,0.16,0.33,0.20,0.20,0.40,0.20,0.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
569,570,Ashley Young,eng ENG,DF,Everton,39.0,1985.0,32,19,1875,...,0.05,0.14,0.19,0.05,0.19,0.01,0.11,0.12,0.01,0.12
570,571,Illia Zabarnyi,ua UKR,DF,Bournemouth,21.0,2002.0,36,35,3109,...,0.00,0.03,0.03,0.00,0.03,0.04,0.02,0.06,0.04,0.06
571,572,Oleksandr Zinchenko,ua UKR,"DF,MF",Arsenal,27.0,1996.0,15,5,527,...,0.00,0.17,0.17,0.00,0.17,0.11,0.03,0.14,0.11,0.14
572,573,Joshua Zirkzee,nl NED,"FW,MF",Manchester Utd,23.0,2001.0,32,14,1402,...,0.19,0.06,0.26,0.19,0.26,0.31,0.10,0.41,0.31,0.41
573,574,Martin Ødegaard,no NOR,MF,Arsenal,25.0,1998.0,30,26,2325,...,0.12,0.31,0.43,0.08,0.39,0.19,0.21,0.40,0.16,0.37

In [39]:
# hiện 1 só cột
df_premier24 = df_premier24[['Rank' , 'tên cầu thủ','Rank' , 'Quốc tịch','Pos' , 'Tuổi','Năm_sinh' , 'Số_trận','Đá_chính' , 'Phút_thi_đấu' , 'Bàn_thắng']]

In [41]:
df_premier24.head()

,Rank,tên cầu thủ,Rank,Quốc tịch,Pos,Tuổi,Năm_sinh,Số_trận,Đá_chính,Phút_thi_đấu,Bàn_thắng
0,1,Max Aarons,1,eng ENG,DF,24.0,2000.0,3,1,86,0.00
1,2,Joshua Acheampong,2,eng ENG,DF,18.0,2006.0,4,2,170,0.00
2,3,Tyler Adams,3,us USA,MF,25.0,1999.0,28,21,1965,0.00
3,4,Tosin Adarabioyo,4,eng ENG,DF,26.0,1997.0,22,15,1409,0.06
4,5,Simon Adingra,5,ci CIV,"FW,MF",22.0,2002.0,29,12,1097,0.16

In [51]:
#hiện bàn thắng trung bình
ban_thang_TB_player = (df_premier24.groupby('tên cầu thủ')['Bàn_thắng'].transform('mean'))
df_premier24['Bàn_thắng_TB_player'] = ban_thang_TB_player
df_premier24 = df_premier24.drop(columns=['Bàn_thắng_TB'])
df_premier24.head(15)

C:\Users\84349\AppData\Local\Temp\ipykernel_12816\4100616347.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_premier24['Bàn_thắng_TB_player'] = ban_thang_TB_player

,Rank,tên cầu thủ,Rank,Quốc tịch,Pos,Tuổi,Năm_sinh,Số_trận,Đá_chính,Phút_thi_đấu,Bàn_thắng,Bàn_thắng_TB_player
0,1,Max Aarons,1,eng ENG,DF,24.0,2000.0,3,1,86,0.00,0.00
1,2,Joshua Acheampong,2,eng ENG,DF,18.0,2006.0,4,2,170,0.00,0.00
2,3,Tyler Adams,3,us USA,MF,25.0,1999.0,28,21,1965,0.00,0.00
3,4,Tosin Adarabioyo,4,eng ENG,DF,26.0,1997.0,22,15,1409,0.06,0.06
4,5,Simon Adingra,5,ci CIV,"FW,MF",22.0,2002.0,29,12,1097,0.16,0.16
5,6,Emmanuel Agbadou,6,ci CIV,DF,27.0,1997.0,16,16,1410,0.06,0.06
6,7,Asher Agbinone,7,eng ENG,MF,18.0,2005.0,2,0,6,0.00,0.00
7,8,Ola Aina,8,ng NGA,DF,27.0,1996.0,35,35,2995,0.06,0.06
8,9,Rayan Aït-Nouri,9,dz ALG,DF,23.0,2001.0,37,37,3109,0.12,0.12
9,10,Kristoffer Ajer,10,no NOR,DF,26.0,1998.0,24,17,1438,0.00,0.00
10,11,Manuel Akanji,11,ch SUI,DF,29.0,1995.0,26,23,2014,0.00,0.00
11,12,Nathan Aké,12,nl NED,DF,29.0,1995.0,10,8,678,0.00,0.00
12,13,Carlos Alcaraz,13,ar ARG,MF,21.0,2002.0,1,0,10,0.00,0.12
13,14,Carlos Alcaraz,14,ar ARG,"FW,MF",21.0,2002.0,15,7,764,0.24,0.12
14,15,Trent Alexander-Arnold,15,eng ENG,DF,25.0,1998.0,33,28,2365,0.11,0.11